# dd_tracer.py - Datadog APM for Python
# Auto-generated by Dobeu Automation Architect
#
# Option 1 (recommended): Run with auto-instrumentation:
#   ddtrace-run python your_app.py
#
# Option 2: Import this module at the top of your main entry point:
#   import dd_tracer  # Must be first import
#
# Required env vars:
#   DD_AGENT_HOST=localhost (or datadog-agent if using Docker sidecar)
#   DD_ENV=production|staging|development
#   DD_SERVICE=your-service-name
#   DD_VERSION=1.0.0

import os
from ddtrace import config, tracer

config.env = os.environ.get("DD_ENV", "production")
config.service = os.environ.get("DD_SERVICE", "dobeu-python-service")
config.version = os.environ.get("DD_VERSION", "1.0.0")

tracer.configure(
    hostname=os.environ.get("DD_AGENT_HOST", "localhost"),
    port=int(os.environ.get("DD_TRACE_AGENT_PORT", "8126")),
)

config.logs_injection = True
