def money: "$" + (tostring);

[
  "# Internal Foundation Readiness",
  "",
  "Generated from snapshot: `\(.generated_from_snapshot)` at \(.generated_at)",
  "",
  "Status: **\(.status)**",
  "",
  "## Boundary",
  "",
  "- External writes allowed: **\(.boundary.external_writes_allowed)**",
  "- Approved task: `\(.boundary.authorized_task_ids | join("`, `"))`",
  "- Excluded actions: \(.boundary.explicitly_excluded | join("; "))",
  "",
  "## Evidence coverage",
  "",
  "- Public repositories: **\(.coverage.public_repositories)**",
  "- Full company repository coverage: **\(.coverage.company_repository_coverage_complete)**",
  "- Supabase projects observed/mapped: **\(.coverage.supabase_projects_observed)/\(.coverage.supabase_projects_mapped)**",
  "- Open evidence conflicts: **\(.coverage.open_conflicts)**",
  "- Baseline artifacts locked by hash: **\(.coverage.baseline_artifacts)**",
  "",
  "## Financial checkpoint",
  "",
  "- Monthly software baseline: **\(.financial.monthly_software_cost_usd | money)**",
  "- Annual software baseline: **\(.financial.annual_software_cost_usd | money)**",
  "- Evidenced collected revenue: **\(.financial.collected_revenue_usd | money)**",
  "- Minimum one-year goal: **\(.financial.minimum_collected_revenue_goal_usd | money)**",
  "- Operating target: **\(.financial.operating_collected_revenue_goal_usd | money)**",
  "",
  "## Blocking evidence",
  "",
  "| Type | ID | Status | Required action | Evidence |",
  "|---|---|---|---|---|",
  (.blockers[] | "| \(.type) | `\(.id)` | \(.status) | \(.action | gsub("[|\\r\\n]"; " ")) | `\(.evidence_ref)` |"),
  "",
  "## Closed approval boundary",
  "",
  "| Gate | Class | Status | Decision required | Owner |",
  "|---|---|---|---|---|",
  (.human_approvals[] | "| \(.approval_id) | \(.approval_class) | \(.status) | \(.action | gsub("[|\\r\\n]"; " ")) | \(.requested_from) |"),
  "",
  "## Next slice",
  "",
  (.next_slice | to_entries[] | "\(.key + 1). \(.value)"),
  "",
  "This report is an internal readiness artifact. It is not permission to expand access, mutate an external system, contact a prospect, change billing, or alter repository lifecycle state."
]
| .[]
